# Form implementation generated from reading ui file 'C:\Users\Пользователь\Desktop\Modeling.ui'
#
# Created by: PyQt 6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QVBoxLayout, QWidget
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg

from Constants import *


class MplCanvas(QtWidgets.QWidget):
    def __init__(self, parent=None):
        QWidget.__init__(self, parent)

        self.canvas = FigureCanvasQTAgg(Figure())

        vertical_layout = QVBoxLayout()
        vertical_layout.addWidget(self.canvas)

        self.canvas.axes = self.canvas.figure.add_subplot()  #: matplotlib.axes.Axes
        self.setLayout(vertical_layout)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("RMR")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.sliderA = QtWidgets.QSlider(parent=self.centralwidget)
        self.sliderA.setGeometry(QtCore.QRect(40, 140, 22, 160))
        self.sliderA.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sliderA.setObjectName("SliderA")
        self.sliderA.setMinimum(SLIDER_MIN)
        self.sliderA.setMaximum(SLIDER_A_MAX * FLOAT_SHIFT)

        self.sliderE = QtWidgets.QSlider(parent=self.centralwidget)
        self.sliderE.setGeometry(QtCore.QRect(130, 140, 22, 160))
        self.sliderE.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sliderE.setObjectName("SliderE")
        self.sliderE.setMinimum(SLIDER_MIN)
        self.sliderE.setMaximum(SLIDER_E_MAX * FLOAT_SHIFT)

        self.sliderT = QtWidgets.QSlider(parent=self.centralwidget)
        self.sliderT.setGeometry(QtCore.QRect(220, 140, 22, 160))
        self.sliderT.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sliderT.setObjectName("SliderT")
        self.sliderT.setMinimum(SLIDER_MIN)
        self.sliderT.setMaximum(SLIDER_T_MAX * FLOAT_SHIFT)

        self.mpl_canvas = MplCanvas(self.centralwidget)
        self.mpl_canvas.setGeometry(QtCore.QRect(280, 20, 510, 441))

        self.buttonGraphPrint = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonGraphPrint.setGeometry(QtCore.QRect(430, 490, 71, 41))
        self.buttonGraphPrint.setObjectName("buttonGraphPrint")

        self.buttonAddGraph = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonAddGraph.setGeometry(QtCore.QRect(570, 490, 71, 41))
        self.buttonAddGraph.setObjectName("buttonAddGraph")

        self.buttonImport = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonImport.setGeometry(QtCore.QRect(60, 490, 71, 41))
        self.buttonImport.setObjectName("buttonImport")

        self.buttonExport = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonExport.setGeometry(QtCore.QRect(150, 490, 71, 41))
        self.buttonExport.setObjectName("buttonExport")

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 110, 16, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 110, 16, 16))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 110, 16, 16))
        self.label_3.setObjectName("label_3")

        self.lineEditA = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditA.setGeometry(QtCore.QRect(30, 310, 41, 20))
        self.lineEditA.setObjectName("lineEditA")

        self.lineEditE = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditE.setGeometry(QtCore.QRect(120, 310, 41, 20))
        self.lineEditE.setObjectName("lineEditE")

        self.lineEditT = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditT.setGeometry(QtCore.QRect(210, 310, 41, 20))
        self.lineEditT.setObjectName("lineEditT")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.dose_label = QtWidgets.QLabel(parent=self.centralwidget)
        # self.dose_label.setGeometry(QtCore.QRect(30, 375, 52, 16))
        # self.dose_label.setObjectName("dose_label")
        #
        # self.lineEditDose = QtWidgets.QLineEdit(parent=self.centralwidget)
        # self.lineEditDose.setGeometry(QtCore.QRect(84, 375, 41, 20))
        # self.lineEditDose.setObjectName("lineEditDose")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("RMR", "RMR"))
        self.buttonGraphPrint.setText(_translate("RMR", "OK"))
        self.buttonAddGraph.setText(_translate("RMR", "ADD"))
        self.buttonImport.setText(_translate("RMR", "Import"))
        self.buttonExport.setText(_translate("RMR", "Export"))
        self.label.setText(_translate("RMR", "α"))
        self.label_2.setText(_translate("RMR", "ε"))
        self.label_3.setText(_translate("RMR", "λt"))
        # self.dose_label.setText(_translate("RMR", "макс доза:"))
